### ISSUE TITLE
no Rubinius support

### ISSUE THREAD

**Issue by paddor** [rspec-given/rspec-given#15]
Can't use it on Rubinius because Rubinius doesn't provide ripper. Maybe you can do something along rspec/rspec-support@81e33d4ed3d980fb3adcbf7f46b13e2444b1a07e.

Thanks very much.

**Comment by paddor** [comment]
@searls Any updates on this? Just tell me if it's not possible/planned to support.

**Comment by searls** [comment]
I'm not a Rubinius user, and I don't plan to address this myself. PRs or
thoughts welcome though

**Comment by paddor** [comment]
Well, neither am I. But I want my gem to run on Rubinius too. :)

How exactly is Ripper used in rspec-given? I see there's [rubinius-ast](https://github.com/rubinius/rubinius-ast) and [rubinius-melbourne](https://github.com/rubinius/rubinius-melbourne). Do you think one of them could be used instead of Ripper?

**Comment by paddor** [comment]
I'm coming up with a hack. The thing is, I really don't care about those detailed failure explanations of natural assertions. All I want is the Then/And block to be evaluated, and if it's false, tell me which test fails. That's all I need. All my natural assertions are in the form of `var == value` or `obj.predicate?`, so very short.

**Comment by paddor** [comment]
@searls Any updates on this?

Some of the specs fail because of another issue. See #18.

**Comment by searls** [comment]
Hey @paddor, I'm going to close this. RSpec itself doesn't support Rubinius (and according to Myron, hasn't for years), so I don't think there's any reason to make an effort to support it in rspec-given.
