### ISSUE TITLE
Unclear how to expect on mocked calls

### ISSUE THREAD

**Issue by thedrow** [rspec-given/rspec-given#25]
rspec-mocks requires you to specify the call expectations before the call to the method under test.
I usually execute the method under test in the When block but that won't work with rspec-mocks.

rspec-mocks forces me to call the method under test in my Then block instead.

Should we provide a different API for checking mocked expectations?

**Comment by francois** [comment]
Reading the docs, I'd say we could probably use a before?

```ruby
before(:each) do
  expect(subject).to receive(:some_method).and_return(:x)
end

When(:result) { subject.some_method }

Then { result == :x }
```

What do you think?

**Comment by thedrow** [comment]
I guess that's what I did eventually.
